language: python

python:
    - "3.4"

install:
    - pip install -r requirements.txt
    - pip install pytest-cov coveralls nose

notifications:
    email: false

after_success: "coveralls"

script: ./bin/run_tests.sh
