language: python

python:
    - "3.4"

install:
    - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then pip install --use-mirrors mock; fi
    - pip install -r requirements.txt --use-mirrors
    - "pip install pytest-cov coveralls"

notifications:
    email: false

after_success: "coveralls"

script: ./bin/run_tests.sh
