language: python

python:
    - "2.6"
    - "2.7"
    - "3.3"

install:
    - if [[ $TRAVIS_PYTHON_VERSION == 2.6 ]]; then pip install --use-mirrors importlib; fi
    - pip install -r requirements.txt --use-mirrors

script: ./bin/run_tests.sh
